### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by joonaoko** [sritala/ot-harjoitustyo#1]
(Ladattu 24.04.2019 13:23)

- GitHubin puolella iso osa luokkien tiedostoista alkaa pienellä kirjaimella (esim. userDao.java), joten jouduin muuttamaan ne alkamaan isolla, että sain testit ja ohjelman toimimaan. Luultavasti muokattu lokaalisti tiedostonnimet oikein, mutta git ei huomaa muutoksia isojen ja pienien kirjaimien välillä, joten muutos ei ole mennyt GitHubiin asti, vaikka kaikki onkin toiminut oikein omalla koneella. Pitäisi saada korjattua muuttamalla nimi joksikin muuksi, ja sitten takaisin alkuperäiseen.

- Pienenä parannusehdotuksena, sisäänkirjautumisen yrittäminen nimellä jota ei löydy voisi antaa käyttäjälle jonkin ilmoituksen, että miksi sisäänkirjautuminen epäonnistui.

- Muodoltaan koodi on selkolukuista. Kaikki muuttujat, metodit jne. on nimetty kuvaavasti, ja yleisesti ottaen koodi on siististi indentoitu ja jäsennelty.

- Mitkään metodit eivät myöskään ole ylimalkaisen pitkiä.

- Lähes kaikki luokat toteuttavat myös nimiensä mukaista yksittäistä asiaa, ja on jaoteltu loogisesti pakkauksiin. Ainoastaan WineArchive-luokan voisi nimetä uusiksi kertomaan että se toteuttaa UI:ta, ja sen voisi sijoittaa uuteen ui-pakkaukseen.

- Koodista ei myöskään löydy luokkia tai metodeja, jotka toteuttavat päällekkäisiä asioita, eli kaikki tekevät sitä mitä kuuluukin, eikä mitään turhaa.

- Pienenä huomautuksena, PaaOhjelma-luokka on nimetty suomeksi, kun kaikki muu on englanniksi.

**Comment by sritala** [comment]
Kiitos palautteesta!
